title: VEP
description: Vix 语言增强提案索引站
lang: zh-CN
timezone: Asia/Shanghai

url: "https://vixlang.github.io"
baseurl: "/VEP"

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  tokenizer_separator: "/[\\s\\-/()]+|(?<=[\\u4e00-\\u9fff])/"
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

heading_anchors: true
color_scheme: light

just_the_docs:
  collections:
    veps:
      name: VEP 提案

plugins:
  - jekyll-feed

collections:
  veps:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "veps"
    values:
      layout: "vep"
  - scope:
      path: ""
    values:
      layout: "default"

